sudo: required

services:
  - docker

script:
  - docker build -t dockerrobotframework:ci .

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_COLOUR_DEPTH=16 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_COLOUR_DEPTH=16 dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_WIDTH=800 -e SCREEN_HEIGHT=600 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_WIDTH=1024 -e SCREEN_HEIGHT=768 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_WIDTH=1280 -e SCREEN_HEIGHT=1024 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_WIDTH=2560 -e SCREEN_HEIGHT=1440 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e SCREEN_WIDTH=3840 -e SCREEN_HEIGHT=2160 dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_WIDTH=800 -e SCREEN_HEIGHT=600 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_WIDTH=1024 -e SCREEN_HEIGHT=768 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_WIDTH=1280 -e SCREEN_HEIGHT=1024 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_WIDTH=2560 -e SCREEN_HEIGHT=1440 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e SCREEN_WIDTH=3840 -e SCREEN_HEIGHT=2160 dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e ROBOT_OPTIONS="--loglevel DEBUG" dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e ROBOT_OPTIONS="--loglevel DEBUG" dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e ROBOT_THREADS=4 dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e ROBOT_THREADS=4 dockerrobotframework:ci

  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome -e ROBOT_THREADS=4 -e PABOT_OPTIONS="--testlevelsplit" dockerrobotframework:ci
  - docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox -e ROBOT_THREADS=4 -e PABOT_OPTIONS="--testlevelsplit" dockerrobotframework:ci

  - docker run --user=2000 --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome dockerrobotframework:ci
  - docker run --user=2000 --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox dockerrobotframework:ci
  - docker run --user=2000:2000 --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=chrome dockerrobotframework:ci
  - docker run --user=2000:2000 --shm-size=1g -v `pwd`/test:/opt/robotframework/tests -e BROWSER=firefox dockerrobotframework:ci
